import streamlit as st

SUPABASE_URL = st.secrets["SUPABASE_URL"]
SUPABASE_API_KEY = st.secrets["SUPABASE_API_KEY"]
OPENAI_API_KEY = st.secrets["OPENAI_API_KEY"]
PREDIBASE_API_TOKEN = st.secrets["PREDIBASE_API_TOKEN"]
PREDIBASE_MODEL_ONE_ADAPT_ID = st.secrets["PREDIBASE_MODEL_ONE_ADAPT_ID"]
PREDIBASE_MODEL_TWO_ADAPT_ID = st.secrets["PREDIBASE_MODEL_TWO_ADAPT_ID"]
NEO4J_URI = st.secrets["NEO4J_URI"]
NEO4J_USER = st.secrets["NEO4J_USER"]
NEO4J_PASSWORD = st.secrets["NEO4J_PASSWORD"]